spring:
  datasource:
    url: jdbc:postgresql://<your AWS endpoint>:5432/student
    username: postgres
    password: your AWS password
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 30
server:
  port: 5000
